# set a specific start time if desired
# start_time: "2015-02-24T18:19:39.12Z"

# amount of time to simulate each tick
tick_duration: 1h

# maximum number of packages to simulate at any point (0 = unlimited)
max_packages: 100_000

# exit after delivering this many packages (0 = unlimited)
max_delivered: 100_000

# number of packages to generate per tick
packages_per_tick:
  avg: 5000
  stddev: 2000

# how long packages should take to be processed
hours_at_rest:
  avg: 4
  stddev: 2

# probability a package is shipped "express"
probability_express: 0.5

# only care about shipping packages at least this far
min_shipping_distance_metres: 100_000

# air freight is pricy - make sure a segment is far enough
min_air_freight_distance_metres: 2_000_000

# average land speed
avg_land_speed_metre_hours: 50_000

# average air speed
avg_air_speed_metre_hours: 750_000

database:
  host: singlestore
  port: 3306
  username: root
  password: root
  database: logistics