verbose: 0
id: local

num_workers: 8

max_delivered: 1_000_000

# sim_interval: 1s
max_packages: 1_000_000

packages_per_tick:
  avg: 100_000
  stddev: 3_000

database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: logistics

topics:
  brokers:
    - 127.0.0.1:9093