version: '3.8'
services:
  redpanda:
    entrypoint:
      - /usr/bin/rpk
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://redpanda:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
    image: vectorized/redpanda:v21.5.5
    container_name: redpanda
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - /var/lib/redpanda/data
  singlestore:
    image: singlestore/cluster-in-a-box:centos-7.3.10-6c220bccfc-3.2.8-1.11.5
    container_name: singlestore
    volumes:
      # persist data between runs:
      - /var/lib/memsql
      - ./schema.sql:/init.sql
      - ./data:/data
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      - ROOT_PASSWORD=root
      - LICENSE_KEY=${SINGLESTORE_LICENSE}
      - START_AFTER_INIT=Y
  simulator:
    build: simulator
    container_name: simulator
    volumes:
      - ./simulator:/go/src/simulator